"""
GrantMirror-AI Report Generator

Produces:
- ESR simulation markdown report
- Coaching markdown report
- Quick dashboard summary
- PDF export from markdown

The functions accept plain Python dictionaries.
"""

from typing import Dict, List, Optional
import re
from io import BytesIO


def generate_esr_report(
    results: Dict,
    eligibility_results: Optional[List[Dict]] = None,
) -> str:
    """Generate ESR-style markdown report."""

    lines = [
        "# 📋 Evaluation Summary Report (ESR Simulation)",
        "",
        f"**Action Type**: {results.get('action_type', 'N/A')}",
        f"**Total Score**: {results.get('total_weighted', 0)}/{results.get('total_max', 0)}",
        f"**Threshold**: {results.get('total_threshold', 0)} — "
        f"{'Met ✅' if results.get('total_threshold_met') else 'Not met ❌'}",
        f"**Funding Probability**: {str(results.get('funding_probability', 'N/A')).upper()}",
        "",
        "*Generated by GrantMirror-AI — Pre-screening tool, not official EC evaluation.*",
        "",
        "---",
        "",
    ]

    if eligibility_results:
        lines.append("## Admissibility & Eligibility Checks")
        lines.append("")

        icon_map = {
            "pass": "✅",
            "fail": "❌",
            "warning": "⚠️",
            "info": "ℹ️",
            "unable": "❓",
        }

        for check in eligibility_results:
            name = check.get("check_name", "Unknown")
            status = check.get("status", "info")
            message = check.get("message", "")
            icon = icon_map.get(status, "ℹ️")
            lines.append(f"- {icon} **{name}**: {message}")

        lines.append("")
        lines.append("---")
        lines.append("")

    for criterion in results.get("criteria", []):
        name = criterion.get("criterion", "N/A")
        score = criterion.get("score", 0)
        max_score = criterion.get("max_score", 5.0)
        threshold = criterion.get("threshold", 3.0)
        weight = criterion.get("weight", 1.0)
        weighted = criterion.get("weighted_score", score * weight)
        confidence_low = criterion.get("confidence_low", "?")
        confidence_high = criterion.get("confidence_high", "?")
        risk = criterion.get("consensus_risk", "N/A")
        threshold_met = "✅" if criterion.get("threshold_met", False) else "❌"

        lines.append(f"## {name}")
        lines.append("")
        lines.append("| Metric | Value |")
        lines.append("|--------|-------|")
        lines.append(f"| Score | **{score}** / {max_score} {threshold_met} |")
        lines.append(f"| Threshold | {threshold} |")
        lines.append(f"| Weight | ×{weight} (weighted: {weighted:.1f}) |")
        lines.append(f"| Confidence Range | {confidence_low} – {confidence_high} |")
        lines.append(f"| Consensus Risk | {risk} |")
        lines.append("")

        esr_comment = criterion.get("esr_comment", "")
        if esr_comment:
            lines.append("### Evaluator Comment")
            lines.append("")
            lines.append(str(esr_comment))
            lines.append("")

        strengths = criterion.get("strengths", [])
        if strengths:
            lines.append("### Strengths")
            lines.append("")
            for item in strengths:
                lines.append(f"- {item}")
            lines.append("")

        weaknesses = criterion.get("weaknesses", [])
        if weaknesses:
            lines.append("### Weaknesses")
            lines.append("")
            for item in weaknesses:
                lines.append(f"- {item}")
            lines.append("")

        weakness_categories = criterion.get("weakness_categories", [])
        if weakness_categories:
            lines.append(
                f"**Weakness categories**: {', '.join(str(x) for x in weakness_categories)}"
            )
            lines.append("")

        sub_assessments = criterion.get("sub_signal_assessments", [])
        if sub_assessments:
            lines.append("### Sub-signal Assessments")
            lines.append("")
            lines.append("| Signal | Rating | Comment |")
            lines.append("|--------|--------|---------|")

            for assessment in sub_assessments:
                signal = assessment.get("signal", "?")
                rating = assessment.get("rating", "?")
                comment = str(assessment.get("comment", ""))

                if len(comment) > 80:
                    comment = comment[:77] + "..."

                lines.append(f"| {signal} | {rating} | {comment} |")

            lines.append("")

        alternative = criterion.get("alternative_reading", "")
        if alternative:
            lines.append("### Alternative Reading")
            lines.append("")
            lines.append(f"_{alternative}_")
            lines.append("")

        topic_alignment = criterion.get("topic_alignment", "")
        if topic_alignment:
            lines.append("### Topic Alignment")
            lines.append("")
            lines.append(str(topic_alignment))
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append("## Overall Assessment")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(
        f"| Total Weighted Score | **{results.get('total_weighted', 0)}** / {results.get('total_max', 0)} |"
    )
    lines.append(f"| Total Threshold | {results.get('total_threshold', 0)} |")
    lines.append(
        f"| All Criteria Met | {'Yes ✅' if results.get('all_criteria_met') else 'No ❌'} |"
    )
    lines.append(
        f"| Overall Threshold Met | {'Yes ✅' if results.get('total_threshold_met') else 'No ❌'} |"
    )
    lines.append(
        f"| Funding Probability | **{str(results.get('funding_probability', 'N/A')).upper()}** |"
    )
    lines.append("")

    lines.append("### Per-Criterion Summary")
    lines.append("")
    lines.append("| Criterion | Score | Threshold | Status |")
    lines.append("|-----------|-------|-----------|--------|")

    for criterion in results.get("criteria", []):
        name = criterion.get("criterion", "?")
        score = criterion.get("score", 0)
        threshold = criterion.get("threshold", 0)
        status = "✅ Met" if criterion.get("threshold_met", False) else "❌ Not met"
        lines.append(f"| {name} | {score} | {threshold} | {status} |")

    lines.append("")

    cross_cutting = results.get("cross_cutting_issues", [])
    if cross_cutting:
        lines.append("### Cross-cutting Issues")
        lines.append("")

        for issue in cross_cutting:
            lines.append(f"- ⚠️ {issue}")

        lines.append("")

    double_penalty = results.get("double_penalization_warnings", [])
    if double_penalty:
        lines.append("### Double Penalisation Warnings")
        lines.append("")

        for warning in double_penalty:
            lines.append(f"- ⚠️ {warning}")

        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*⚠️ DISCLAIMER: This is an AI-generated evaluation simulation produced by GrantMirror-AI. "
        "It does not replace official European Commission evaluation. Actual scores depend on "
        "evaluator expertise, panel dynamics, call competition, and portfolio considerations. "
        "Use as a pre-screening and proposal improvement tool only.*"
    )

    return "\n".join(lines)


def generate_coaching_report(results: Dict) -> str:
    """Generate coaching/improvement markdown report."""

    lines = [
        "# 🎯 Proposal Improvement Report (Coaching Mode)",
        "",
        f"**Action Type**: {results.get('action_type', 'N/A')}",
        f"**Current Score**: {results.get('total_weighted', 0)} / {results.get('total_max', 0)}",
        f"**Threshold**: {results.get('total_threshold', 0)} — "
        f"{'Above ✅' if results.get('total_threshold_met') else 'Below ❌'}",
        f"**Funding Probability**: {str(results.get('funding_probability', 'N/A')).upper()}",
        "",
        "---",
        "",
    ]

    lines.append("## Score Overview")
    lines.append("")

    for criterion in results.get("criteria", []):
        name = criterion.get("criterion", "?")
        score = criterion.get("score", 0)
        max_score = criterion.get("max_score", 5.0)
        threshold = criterion.get("threshold", 3.0)

        bar_len = 20
        filled = int(score / max_score * bar_len) if max_score > 0 else 0
        filled = max(0, min(bar_len, filled))
        empty = bar_len - filled
        bar = "█" * filled + "░" * empty
        status = " ⚠️ BELOW THRESHOLD" if score < threshold else ""

        lines.append(f"**{name}**: `{bar}` {score}/{max_score}{status}")

    lines.append("")
    lines.append("---")
    lines.append("")

    for coaching in results.get("coaching", []):
        name = coaching.get("criterion", "N/A")

        criterion_score = 0
        for criterion in results.get("criteria", []):
            if criterion.get("criterion") == name:
                criterion_score = criterion.get("score", 0)
                break

        emoji = "🟢" if criterion_score >= 4 else "🟡" if criterion_score >= 3 else "🔴"

        lines.append(f"## {emoji} {name} (Score: {criterion_score}/5.0)")
        lines.append("")

        improvements = coaching.get("improvements", [])

        if improvements:
            lines.append("### Improvement Actions")
            lines.append("")

            for improvement in improvements:
                priority = improvement.get("priority", "?")
                title = improvement.get("title", "N/A")
                gain = improvement.get("expected_score_gain", "?")

                lines.append(f"#### 🔧 Priority {priority}: {title}")
                lines.append(f"**Expected gain**: {gain}")
                lines.append("")

                problem = improvement.get("problem", "")
                if problem:
                    lines.append(f"**Problem**: {problem}")
                    lines.append("")

                impact = improvement.get("impact", "")
                if impact:
                    lines.append(f"**Why it hurts the score**: {impact}")
                    lines.append("")

                solution = improvement.get("solution", "")
                if solution:
                    lines.append(f"**How to fix**: {solution}")
                    lines.append("")

        else:
            lines.append("_No specific improvements generated for this criterion._")
            lines.append("")

        summary = coaching.get("summary", "")
        if summary:
            lines.append(f"**Overall coaching advice**: {summary}")
            lines.append("")

        lines.append("---")
        lines.append("")

    cross_cutting = results.get("cross_cutting_issues", [])
    if cross_cutting:
        lines.append("## 🔄 Systemic Issues")
        lines.append("")
        lines.append(
            "These issues affect your overall proposal quality and should be addressed first:"
        )
        lines.append("")

        for issue in cross_cutting:
            lines.append(f"- ⚠️ {issue}")

        lines.append("")
        lines.append("---")
        lines.append("")

    lines.append("## ✅ Resubmission Checklist")
    lines.append("")

    all_improvements = []

    for coaching in results.get("coaching", []):
        name = coaching.get("criterion", "?")

        for improvement in coaching.get("improvements", []):
            all_improvements.append(
                {
                    "criterion": name,
                    "priority": improvement.get("priority", 99),
                    "title": improvement.get("title", ""),
                    "gain": improvement.get("expected_score_gain", "?"),
                }
            )

    all_improvements.sort(key=lambda x: x["priority"])

    if all_improvements:
        lines.append("| # | Criterion | Action | Expected Gain | Done |")
        lines.append("|---|-----------|--------|---------------|------|")

        for i, improvement in enumerate(all_improvements[:10], 1):
            title = improvement["title"]

            if len(title) > 50:
                title = title[:47] + "..."

            lines.append(
                f"| {i} | {improvement['criterion']} | {title} | {improvement['gain']} | ☐ |"
            )

        lines.append("")
    else:
        lines.append("_No specific action items generated._")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "*💡 This coaching report is generated by GrantMirror-AI based on Horizon Europe "
        "evaluation patterns from ESR analysis. Consider consulting with your National Contact "
        "Point or experienced proposal writers for additional guidance.*"
    )

    return "\n".join(lines)


def generate_quick_summary(results: Dict) -> str:
    """One-paragraph summary for dashboard display."""

    scores = ", ".join(
        f"{criterion.get('criterion', '?')}: {criterion.get('score', 0)}"
        for criterion in results.get("criteria", [])
    )

    threshold_label = "above" if results.get("total_threshold_met") else "below"
    probability = results.get("funding_probability", "N/A")

    return (
        f"**{results.get('action_type', '?')}** — "
        f"Scores: {scores}. "
        f"Total: {results.get('total_weighted', 0)}/{results.get('total_max', 0)} "
        f"({threshold_label} threshold {results.get('total_threshold', 0)}). "
        f"Funding probability: **{probability}**."
    )


def _escape_xml(text: str) -> str:
    if text is None:
        return ""

    return (
        str(text)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def _markdown_line_to_html(line: str) -> str:
    """Convert a simple markdown line into ReportLab-safe inline HTML."""

    line = _escape_xml(line.strip())

    # Bold markdown
    line = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", line)

    # Italic markdown
    line = re.sub(r"_(.*?)_", r"<i>\1</i>", line)

    return line


def markdown_to_pdf_bytes(markdown_text: str) -> bytes:
    """
    Convert simple markdown into PDF bytes.

    Requires:
        reportlab>=4.0.0
    """

    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
    except ImportError as exc:
        raise ImportError(
            "reportlab bulunamadı. requirements.txt içine `reportlab>=4.0.0` ekleyin."
        ) from exc

    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.8 * cm,
        leftMargin=1.8 * cm,
        topMargin=1.6 * cm,
        bottomMargin=1.6 * cm,
    )

    styles = getSampleStyleSheet()

    body_style = ParagraphStyle(
        "GMBody",
        parent=styles["BodyText"],
        fontSize=9,
        leading=12,
        spaceAfter=6,
    )

    bullet_style = ParagraphStyle(
        "GMBullet",
        parent=body_style,
        leftIndent=12,
        firstLineIndent=-8,
    )

    h1_style = ParagraphStyle(
        "GMHeading1",
        parent=styles["Heading1"],
        fontSize=16,
        leading=20,
        spaceBefore=8,
        spaceAfter=10,
    )

    h2_style = ParagraphStyle(
        "GMHeading2",
        parent=styles["Heading2"],
        fontSize=13,
        leading=16,
        spaceBefore=10,
        spaceAfter=7,
    )

    h3_style = ParagraphStyle(
        "GMHeading3",
        parent=styles["Heading3"],
        fontSize=11,
        leading=14,
        spaceBefore=8,
        spaceAfter=6,
    )

    story = []

    for raw_line in markdown_text.splitlines():
        line = raw_line.strip()

        if not line:
            story.append(Spacer(1, 6))
            continue

        if line == "---":
            story.append(Spacer(1, 10))
            continue

        if line.startswith("# "):
            story.append(Paragraph(_markdown_line_to_html(line[2:]), h1_style))
            continue

        if line.startswith("## "):
            story.append(Paragraph(_markdown_line_to_html(line[3:]), h2_style))
            continue

        if line.startswith("### "):
            story.append(Paragraph(_markdown_line_to_html(line[4:]), h3_style))
            continue

        if line.startswith("#### "):
            story.append(Paragraph(f"<b>{_markdown_line_to_html(line[5:])}</b>", h3_style))
            continue

        if line.startswith("- "):
            story.append(
                Paragraph("• " + _markdown_line_to_html(line[2:]), bullet_style)
            )
            continue

        # Markdown tables are rendered as monospaced-ish text blocks for stability.
        if line.startswith("|"):
            story.append(Paragraph(_markdown_line_to_html(line), body_style))
            continue

        story.append(Paragraph(_markdown_line_to_html(line), body_style))

    doc.build(story)

    pdf_bytes = buffer.getvalue()
    buffer.close()

    return pdf_bytes
