"""
GrantMirror-AI Report Generator
Produces ESR simulation and coaching markdown reports.
Zero local dependencies — accepts only Python dicts.
"""
from typing import Dict, List, Optional


def generate_esr_report(results: Dict, eligibility_results: Optional[List[Dict]] = None) -> str:
    """
    Generate ESR-style markdown report.
    
    Args:
        results: Full evaluation results dict from Evaluator.run()
        eligibility_results: Optional list of dicts with keys: check_name, status, message
    """
    lines = [
        "# 📋 Evaluation Summary Report (ESR Simulation)",
        "",
        f"**Action Type**: {results.get('action_type', 'N/A')}",
        f"**Total Score**: {results.get('total_weighted', 0)}/{results.get('total_max', 0)}",
        f"**Threshold**: {results.get('total_threshold', 0)} — "
        f"{'Met ✅' if results.get('total_threshold_met') else 'Not met ❌'}",
        f"**Funding Probability**: {results.get('funding_probability', 'N/A').upper()}",
        "",
        f"*Generated by GrantMirror-AI — Pre-screening tool, not official EC evaluation.*",
        "",
        "---",
        "",
    ]

    # ── Eligibility section ──
    if eligibility_results:
        lines.append("## Admissibility & Eligibility Checks")
        lines.append("")
        icon_map = {
            "pass": "✅",
            "fail": "❌",
            "warning": "⚠️",
            "info": "ℹ️",
            "unable": "❓",
        }
        for ch in eligibility_results:
            name = ch.get("check_name", "Unknown")
            status = ch.get("status", "info")
            msg = ch.get("message", "")
            icon = icon_map.get(status, "")
            lines.append(f"- {icon} **{name}**: {msg}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Per-criterion evaluation ──
    for crit in results.get("criteria", []):
        name = crit.get("criterion", "N/A")
        score = crit.get("score", 0)
        mx = crit.get("max_score", 5.0)
        thr = crit.get("threshold", 3.0)
        weight = crit.get("weight", 1.0)
        weighted = crit.get("weighted_score", score * weight)
        conf_lo = crit.get("confidence_low", "?")
        conf_hi = crit.get("confidence_high", "?")
        risk = crit.get("consensus_risk", "N/A")
        met = "✅" if crit.get("threshold_met", False) else "❌"

        lines.append(f"## {name}")
        lines.append("")
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Score | **{score}** / {mx} {met} |")
        lines.append(f"| Threshold | {thr} |")
        lines.append(f"| Weight | ×{weight} (weighted: {weighted:.1f}) |")
        lines.append(f"| Confidence Range | {conf_lo} – {conf_hi} |")
        lines.append(f"| Consensus Risk | {risk} |")
        lines.append("")

        # ESR Comment
        esr = crit.get("esr_comment", "")
        if esr:
            lines.append("### Evaluator Comment")
            lines.append("")
            lines.append(esr)
            lines.append("")

        # Strengths
        strengths = crit.get("strengths", [])
        if strengths:
            lines.append("### Strengths")
            lines.append("")
            for s in strengths:
                lines.append(f"- {s}")
            lines.append("")

        # Weaknesses
        weaknesses = crit.get("weaknesses", [])
        if weaknesses:
            lines.append("### Weaknesses")
            lines.append("")
            for w in weaknesses:
                lines.append(f"- {w}")
            lines.append("")

        # Weakness categories
        cats = crit.get("weakness_categories", [])
        if cats:
            lines.append(f"**Weakness categories**: {', '.join(cats)}")
            lines.append("")

        # Sub-signal assessments
        subs = crit.get("sub_signal_assessments", [])
        if subs:
            lines.append("### Sub-signal Assessments")
            lines.append("")
            lines.append("| Signal | Rating | Comment |")
            lines.append("|--------|--------|---------|")
            for sa in subs:
                sig = sa.get("signal", "?")
                rating = sa.get("rating", "?")
                comment = sa.get("comment", "")
                # Truncate long comments for table
                if len(comment) > 80:
                    comment = comment[:77] + "..."
                lines.append(f"| {sig} | {rating} | {comment} |")
            lines.append("")

        # Alternative reading
        alt = crit.get("alternative_reading", "")
        if alt:
            lines.append("### Alternative Reading")
            lines.append("")
            lines.append(f"_{alt}_")
            lines.append("")

        lines.append("---")
        lines.append("")

    # ── Overall summary ──
    lines.append("## Overall Assessment")
    lines.append("")
    lines.append(f"| Metric | Value |")
    lines.append(f"|--------|-------|")
    lines.append(f"| Total Weighted Score | **{results.get('total_weighted', 0)}** / {results.get('total_max', 0)} |")
    lines.append(f"| Total Threshold | {results.get('total_threshold', 0)} |")
    lines.append(f"| All Criteria Met | {'Yes ✅' if results.get('all_criteria_met') else 'No ❌'} |")
    lines.append(f"| Overall Threshold Met | {'Yes ✅' if results.get('total_threshold_met') else 'No ❌'} |")
    lines.append(f"| Funding Probability | **{results.get('funding_probability', 'N/A').upper()}** |")
    lines.append("")

    # Per-criterion threshold summary
    lines.append("### Per-Criterion Summary")
    lines.append("")
    lines.append("| Criterion | Score | Threshold | Status |")
    lines.append("|-----------|-------|-----------|--------|")
    for crit in results.get("criteria", []):
        name = crit.get("criterion", "?")
        score = crit.get("score", 0)
        thr = crit.get("threshold", 0)
        met = "✅ Met" if crit.get("threshold_met", False) else "❌ Not met"
        lines.append(f"| {name} | {score} | {thr} | {met} |")
    lines.append("")

    # Cross-cutting issues
    cross = results.get("cross_cutting_issues", [])
    if cross:
        lines.append("### Cross-cutting Issues")
        lines.append("")
        for iss in cross:
            lines.append(f"- ⚠️ {iss}")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*⚠️ DISCLAIMER: This is an AI-generated evaluation simulation produced by GrantMirror-AI. "
                  "It does not replace official European Commission evaluation. Actual scores depend on "
                  "evaluator expertise, panel dynamics, call competition, and portfolio considerations. "
                  "Use as a pre-screening and proposal improvement tool only.*")

    return "\n".join(lines)


def generate_coaching_report(results: Dict) -> str:
    """
    Generate coaching/improvement markdown report.
    Unlike ESR: provides specific suggestions, prioritized by impact.
    """
    lines = [
        "# 🎯 Proposal Improvement Report (Coaching Mode)",
        "",
        f"**Action Type**: {results.get('action_type', 'N/A')}",
        f"**Current Score**: {results.get('total_weighted', 0)} / {results.get('total_max', 0)}",
        f"**Threshold**: {results.get('total_threshold', 0)} — "
        f"{'Above ✅' if results.get('total_threshold_met') else 'Below ❌'}",
        f"**Funding Probability**: {results.get('funding_probability', 'N/A').upper()}",
        "",
        "---",
        "",
    ]

    # ── Score overview ──
    lines.append("## Score Overview")
    lines.append("")
    for crit in results.get("criteria", []):
        name = crit.get("criterion", "?")
        score = crit.get("score", 0)
        mx = crit.get("max_score", 5.0)
        thr = crit.get("threshold", 3.0)
        bar_len = 20
        filled = int(score / mx * bar_len) if mx > 0 else 0
        empty = bar_len - filled
        bar = "█" * filled + "░" * empty
        status = " ⚠️ BELOW THRESHOLD" if score < thr else ""
        lines.append(f"**{name}**: `{bar}` {score}/{mx}{status}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # ── Per-criterion coaching ──
    for coaching in results.get("coaching", []):
        name = coaching.get("criterion", "N/A")

        # Find matching criterion score
        crit_score = 0
        for crit in results.get("criteria", []):
            if crit.get("criterion") == name:
                crit_score = crit.get("score", 0)
                break

        emoji = "🟢" if crit_score >= 4 else "🟡" if crit_score >= 3 else "🔴"
        lines.append(f"## {emoji} {name} (Score: {crit_score}/5.0)")
        lines.append("")

        # Improvements
        improvements = coaching.get("improvements", [])
        if improvements:
            lines.append("### Improvement Actions")
            lines.append("")

            for imp in improvements:
                priority = imp.get("priority", "?")
                title = imp.get("title", "N/A")
                gain = imp.get("expected_score_gain", "?")

                lines.append(f"#### 🔧 Priority {priority}: {title}")
                lines.append(f"**Expected gain**: {gain}")
                lines.append("")

                problem = imp.get("problem", "")
                if problem:
                    lines.append(f"**Problem**: {problem}")
                    lines.append("")

                impact = imp.get("impact", "")
                if impact:
                    lines.append(f"**Why it hurts the score**: {impact}")
                    lines.append("")

                solution = imp.get("solution", "")
                if solution:
                    lines.append(f"**How to fix**: {solution}")
                    lines.append("")
        else:
            lines.append("_No specific improvements generated for this criterion._")
            lines.append("")

        # Summary
        summary = coaching.get("summary", "")
        if summary:
            lines.append(f"**Overall coaching advice**: {summary}")
            lines.append("")

        lines.append("---")
        lines.append("")

    # ── Cross-cutting issues ──
    cross = results.get("cross_cutting_issues", [])
    if cross:
        lines.append("## 🔄 Systemic Issues (appear across multiple criteria)")
        lines.append("")
        lines.append("These issues affect your overall proposal quality and should be addressed first:")
        lines.append("")
        for iss in cross:
            lines.append(f"- ⚠️ {iss}")
        lines.append("")
        lines.append("---")
        lines.append("")

    # ── Resubmission checklist ──
    lines.append("## ✅ Resubmission Checklist")
    lines.append("")

    all_improvements = []
    for coaching in results.get("coaching", []):
        name = coaching.get("criterion", "?")
        for imp in coaching.get("improvements", []):
            all_improvements.append({
                "criterion": name,
                "priority": imp.get("priority", 99),
                "title": imp.get("title", ""),
                "gain": imp.get("expected_score_gain", "?"),
            })

    # Sort by priority
    all_improvements.sort(key=lambda x: x["priority"])

    if all_improvements:
        lines.append("| # | Criterion | Action | Expected Gain | Done |")
        lines.append("|---|-----------|--------|---------------|------|")
        for i, imp in enumerate(all_improvements[:10], 1):
            title = imp["title"]
            if len(title) > 50:
                title = title[:47] + "..."
            lines.append(f"| {i} | {imp['criterion']} | {title} | {imp['gain']} | ☐ |")
        lines.append("")
    else:
        lines.append("_No specific action items generated._")
        lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*💡 This coaching report is generated by GrantMirror-AI based on Horizon Europe "
                  "evaluation patterns from ESR analysis (LERU, NCP, Danish UFDS studies). "
                  "Consider consulting with your National Contact Point or experienced proposal "
                  "writers for additional guidance.*")

    return "\n".join(lines)


def generate_quick_summary(results: Dict) -> str:
    """One-paragraph summary for dashboard display."""
    scores = ", ".join(
        f"{c.get('criterion', '?')}: {c.get('score', 0)}"
        for c in results.get("criteria", [])
    )
    met = "above" if results.get("total_threshold_met") else "below"
    prob = results.get("funding_probability", "N/A")

    return (
        f"**{results.get('action_type', '?')}** — "
        f"Scores: {scores}. "
        f"Total: {results.get('total_weighted', 0)}/{results.get('total_max', 0)} "
        f"({met} threshold {results.get('total_threshold', 0)}). "
        f"Funding probability: **{prob}**."
    )
